# Generated by Django 3.1.3 on 2021-01-08 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsetcases',
            name='interface',
            field=models.ForeignKey(help_text='所属接口', null=True, on_delete=django.db.models.deletion.CASCADE, to='interfaces.interfaces'),
        ),
    ]
