# Generated by Django 3.1.3 on 2021-01-08 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
        ('testcases', '0003_auto_20210108_1011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tsetcases',
            new_name='Testcases',
        ),
    ]
