# Generated by Django 3.1.3 on 2020-11-17 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projects'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='tb_projects',
        ),
    ]
