# Generated by Django 3.1.3 on 2020-11-17 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20201117_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
    ]
