# Generated by Django 3.1.3 on 2020-11-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20201117_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '人员', 'verbose_name_plural': '人员'},
        ),
    ]
